package maven.jdbc.cinema.exceptions;

public enum ExceptionCode
{
    DATABASE,
    BUILDER,
    JSON_PARSER,
    DATA_MANAGER,
    REPOSITORY,
    REPOSITORY_CUSTOMER,
    REPOSITORY_LOYALTY_CARD,
    REPOSITORY_MOVIE,
    REPOSITORY_TICKET,
    SERVICE,
    SERVICE_PURCHASE,
    SERVICE_HISTORY,
    SERVICE_STATISTICS,
    SERVICE_MENU,
    SERVICE_EMAIL,
    SERVICE_SCANNER,
    SERVICE_CUSTOMER,
    SERVICE_MOVIE,
    SERVICE_TICKET,
    SERVICE_LOYALTY_CARD
}
